version: '3.8'

services:
  postgres:
    build: ./apps/postgresdb
    container_name: postgresdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  prune_server:
    build: ./apps/prune_server
    container_name: prune_server
    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgresdb
      DB_PORT: 5432
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - postgres
